# PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andreas-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreas-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andreas-postgres
  template:
    metadata:
      labels:
        app: andreas-postgres
    spec:
      containers:
        - name: andreas-postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi

          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: andreas-db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andreas-db-password
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: andreas-db-config
                  key: db-name
          volumeMounts:
            - name: andreas-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: andreas-postgres-data
          persistentVolumeClaim:
            claimName: andreas-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: andreas-postgres
spec:
  type: ClusterIP
  selector:
    app: andreas-postgres
  ports:
    - port: 5432
---
# Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andreas-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreas-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andreas-redis
  template:
    metadata:
      labels:
        app: andreas-redis
    spec:
      containers:
        - name: andreas-redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andreas-redis-password
                  key: password
          volumeMounts:
            - name: andreas-redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: andreas-redis-data
          persistentVolumeClaim:
            claimName: andreas-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: andreas-redis
spec:
  type: ClusterIP
  selector:
    app: andreas-redis
  ports:
    - port: 6379

# Golang Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreas-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: andreas-backend
  template:
    metadata:
      labels:
        app: andreas-backend
    spec:
      containers:
        - name: andreas-backend
          image: ghcr.io/hardomx/guestbook-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: andreas-db-config
                  key: db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: andreas-db-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: andreas-db-config
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andreas-redis-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: andreas-backend
spec:
  type: ClusterIP
  selector:
    app: andreas-backend
  ports:
    - port: 8080
