apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreas-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: andreas-frontend
  template:
    metadata:
      labels:
        app: andreas-frontend
    spec:
      containers:
        - name: andreas-frontend
          image: ghcr.io/hardomx/guestbook-frontend:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: andreas-frontend
spec:
  type: ClusterIP
  selector:
    app: andreas-frontend
  ports:
    - port: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: andreas-frontend
spec:
  to:
    kind: Service
    name: andreas-frontend
